package com.hbs.language.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@DynamoDBTable(tableName = "language")
public class Word {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String wordId;

    @DynamoDBAttribute
    private String english;

    @DynamoDBAttribute
    private String german;

    @DynamoDBAttribute
    private String article;
}
